export type McpSurface = "server" | "cli" | "worker";

export type McpToolContract = {
  name: string;
  surfaces: readonly McpSurface[];
};

const ALL_SURFACES = ["server", "cli", "worker"] as const;
const CLI_ONLY = ["cli"] as const;

export const MCP_TOOL_CONTRACTS = [
  { name: "trunk_ack_bulk", surfaces: ALL_SURFACES },
  { name: "trunk_analytics", surfaces: ALL_SURFACES },
  { name: "trunk_audit_log", surfaces: ALL_SURFACES },
  { name: "trunk_billing", surfaces: ALL_SURFACES },
  { name: "trunk_block_contact", surfaces: ALL_SURFACES },
  { name: "trunk_blocked_list", surfaces: ALL_SURFACES },
  { name: "trunk_cancel_scheduled", surfaces: ALL_SURFACES },
  { name: "trunk_config", surfaces: ALL_SURFACES },
  { name: "trunk_contact_note", surfaces: ALL_SURFACES },
  { name: "trunk_contact_tags", surfaces: ALL_SURFACES },
  { name: "trunk_contacts", surfaces: ALL_SURFACES },
  { name: "trunk_create_template", surfaces: ALL_SURFACES },
  { name: "trunk_delete_attachment", surfaces: ALL_SURFACES },
  { name: "trunk_delete_bulk", surfaces: ALL_SURFACES },
  { name: "trunk_delete_contact_note", surfaces: ALL_SURFACES },
  { name: "trunk_delete_message", surfaces: ALL_SURFACES },
  { name: "trunk_delete_template", surfaces: ALL_SURFACES },
  { name: "trunk_deliver_scheduled", surfaces: ALL_SURFACES },
  { name: "trunk_document", surfaces: ALL_SURFACES },
  { name: "trunk_document_versions", surfaces: ALL_SURFACES },
  { name: "trunk_edit_message", surfaces: ALL_SURFACES },
  { name: "trunk_fact", surfaces: ALL_SURFACES },
  { name: "trunk_forward", surfaces: ALL_SURFACES },
  { name: "trunk_gantt", surfaces: ALL_SURFACES },
  { name: "trunk_get_attachment", surfaces: ALL_SURFACES },
  { name: "trunk_inbox", surfaces: ALL_SURFACES },
  { name: "trunk_inbox_stats", surfaces: ALL_SURFACES },
  { name: "trunk_label_bulk", surfaces: ALL_SURFACES },
  { name: "trunk_label_message", surfaces: ALL_SURFACES },
  { name: "trunk_labels_list", surfaces: ALL_SURFACES },
  { name: "trunk_list_attachments", surfaces: ALL_SURFACES },
  { name: "trunk_list_templates", surfaces: ALL_SURFACES },
  { name: "trunk_mark_read", surfaces: ALL_SURFACES },
  { name: "trunk_message_attachments", surfaces: ALL_SURFACES },
  { name: "trunk_message_edit_history", surfaces: ALL_SURFACES },
  { name: "trunk_message_labels", surfaces: ALL_SURFACES },
  { name: "trunk_messages_by_label", surfaces: ALL_SURFACES },
  { name: "trunk_notification_prefs", surfaces: ALL_SURFACES },
  { name: "trunk_pair", surfaces: ALL_SURFACES },
  { name: "trunk_pin", surfaces: ALL_SURFACES },
  { name: "trunk_presence", surfaces: ALL_SURFACES },
  { name: "trunk_profile", surfaces: ALL_SURFACES },
  { name: "trunk_purge_messages", surfaces: ALL_SURFACES },
  { name: "trunk_react", surfaces: ALL_SURFACES },
  { name: "trunk_reactions", surfaces: ALL_SURFACES },
  { name: "trunk_read_bulk", surfaces: ALL_SURFACES },
  { name: "trunk_register", surfaces: ALL_SURFACES },
  { name: "trunk_reply", surfaces: ALL_SURFACES },
  { name: "trunk_room", surfaces: ALL_SURFACES },
  { name: "trunk_room_webhook", surfaces: ALL_SURFACES },
  { name: "trunk_saved_searches", surfaces: ALL_SURFACES },
  { name: "trunk_scheduled_messages", surfaces: ALL_SURFACES },
  { name: "trunk_search", surfaces: ALL_SURFACES },
  { name: "trunk_send", surfaces: ALL_SURFACES },
  { name: "trunk_sent", surfaces: ALL_SURFACES },
  { name: "trunk_set_contact_note", surfaces: ALL_SURFACES },
  { name: "trunk_set_status", surfaces: ALL_SURFACES },
  { name: "trunk_tag_contact", surfaces: ALL_SURFACES },
  { name: "trunk_task_create", surfaces: ALL_SURFACES },
  { name: "trunk_task_delete", surfaces: ALL_SURFACES },
  { name: "trunk_task_list", surfaces: ALL_SURFACES },
  { name: "trunk_task_update", surfaces: ALL_SURFACES },
  { name: "trunk_thread", surfaces: ALL_SURFACES },
  { name: "trunk_thread_pins", surfaces: ALL_SURFACES },
  { name: "trunk_thread_summary", surfaces: ALL_SURFACES },
  { name: "trunk_threads", surfaces: ALL_SURFACES },
  { name: "trunk_unblock_contact", surfaces: ALL_SURFACES },
  { name: "trunk_unlabel_message", surfaces: ALL_SURFACES },
  { name: "trunk_unpair", surfaces: ALL_SURFACES },
  { name: "trunk_unpin", surfaces: ALL_SURFACES },
  { name: "trunk_unreact", surfaces: ALL_SURFACES },
  { name: "trunk_untag_contact", surfaces: ALL_SURFACES },
  { name: "trunk_update_contact", surfaces: ALL_SURFACES },
  { name: "trunk_update_template", surfaces: ALL_SURFACES },
  { name: "trunk_upload_attachment", surfaces: ALL_SURFACES },
  { name: "trunk_webhook", surfaces: ALL_SURFACES },
  { name: "trunk_workspace", surfaces: ALL_SURFACES },
  { name: "trunk_project", surfaces: CLI_ONLY },
  { name: "trunk_status", surfaces: CLI_ONLY },
] as const satisfies readonly McpToolContract[];

export const MCP_TOOL_NAMES = MCP_TOOL_CONTRACTS.map((tool) => tool.name);
